# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TGTV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TGTV
pod 'Alamofire'
pod 'Kingfisher'
pod 'SnapKit'
pod 'SDCycleScrollView'
pod 'ProtocolBuffers-Swift'
pod 'MJExtension'
end
